### PR TITLE
Add tests for extract.py

### PR DESCRIPTION
**Pull request by sarina**

### CODE REVIEW

**Comment by sarina** [comment]
@nedbat I have no idea what I was attempting to do here

**Comment by edx-webhook** [comment]
Thanks for the pull request, @sarina! I've created [OSPR-1049](https://openedx.atlassian.net/browse/OSPR-1049) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by singingwolfboy** [comment]
@sarina: in that case, should this pull request be closed?

**Comment by nedbat** [comment]
I'll own this PR now.

**Pull request closed without merging**
